<script setup>
import { computed, onMounted, ref } from 'vue'
import { useBackOfficeStore } from './stores/backOffice'
import logo from './assets/logo.jpeg'
import { productImageUrl } from './lib/supabase'
const store = useBackOfficeStore()
const passwordVisible = ref(false)
const mobileMenuOpen = ref(false)
onMounted(() => store.initialise())
const nav = [{ id: 'orders', label: 'Orders', icon: 'receipt_long' }, { id: 'customers', label: 'Customers', icon: 'group' }, { id: 'products', label: 'Products', icon: 'inventory_2' }, { id: 'delivery-methods', label: 'Delivery methods', icon: 'local_shipping' }]
const title = computed(() => store.activeView === 'order-detail' ? `Order ${store.selectedOrder?.order_number || ''}` : nav.find(item => item.id === store.activeView)?.label || 'Operations')
const money = value => new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES' }).format(Number(value || 0))
const date = value => value ? new Intl.DateTimeFormat('en-KE', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'
const label = value => value?.replaceAll('_', ' ')
const statusClass = value => value === 'paid' || value === 'delivered' ? 'green' : value === 'failed' ? 'red' : value === 'pending' || value === 'awaiting_confirmation' ? 'orange' : 'blue'
</script>

<template>
  <div v-if="!store.ready" class="loading-screen"><img class="loading-logo" :src="logo" alt="Sage Candle KE"></div>
  <section v-else-if="!store.session" class="auth-screen"><form class="auth-card" @submit.prevent="store.signIn"><img class="auth-logo" :src="logo" alt="Sage Candle KE"><p class="eyebrow">Sage Candle KE</p><h1>Operations Console</h1><p>Sign in with an authorised back-office account.</p><label>Email<input v-model="store.credentials.email" type="email" autocomplete="email" required></label><label>Password<div class="password-input"><input v-model="store.credentials.password" :type="passwordVisible ? 'text' : 'password'" autocomplete="current-password" required><button type="button" class="password-toggle material-symbols-outlined" :aria-label="passwordVisible ? 'Hide password' : 'Show password'" :title="passwordVisible ? 'Hide password' : 'Show password'" @click="passwordVisible = !passwordVisible">{{ passwordVisible ? 'visibility_off' : 'visibility' }}</button></div></label><p v-if="store.authError" class="form-error">{{ store.authError }}</p><button class="primary full" :disabled="store.loading">{{ store.loading ? 'Signing in…' : 'Sign in' }}</button></form></section>
  <div v-else class="app-shell">
    <aside class="sidebar" :class="{ 'mobile-open': mobileMenuOpen }"><div class="brand"><img class="brand-logo" :src="logo" alt="Sage Candle KE"><div><h1>Sage Candle</h1><p>Operations Console</p></div></div><nav><button v-for="item in nav" :key="item.id" :class="{ active: store.activeView === item.id || (item.id === 'orders' && store.activeView === 'order-detail') }" @click="store.navigate(item.id); mobileMenuOpen = false"><span class="material-symbols-outlined">{{ item.icon }}</span>{{ item.label }}</button></nav><div class="profile"><div class="avatar material-symbols-outlined">admin_panel_settings</div><div><strong>{{ store.session.user.email }}</strong><small>Authenticated user</small></div><button class="icon material-symbols-outlined" title="Sign out" @click="store.signOut">logout</button></div></aside>
    <button v-if="mobileMenuOpen" class="mobile-menu-backdrop" aria-label="Close navigation" @click="mobileMenuOpen = false"></button>
    <header><div class="page-title"><button class="mobile-menu-toggle material-symbols-outlined" :aria-label="mobileMenuOpen ? 'Close navigation' : 'Open navigation'" @click="mobileMenuOpen = !mobileMenuOpen">{{ mobileMenuOpen ? 'close' : 'menu' }}</button><h2>{{ title }}</h2></div><div class="header-actions"><button class="outline" :disabled="store.loading" @click="store.loadData"><span class="material-symbols-outlined">refresh</span>Refresh</button></div></header>
    <main><p v-if="store.dataError" class="data-error"><span class="material-symbols-outlined">error</span>{{ store.dataError }} <button @click="store.loadData">Retry</button></p>
      <section v-if="store.activeView === 'orders'" class="page"><div class="page-heading"><div><p class="eyebrow">Delivery operations</p><h3>Order Registry</h3><p>Manage fulfilment with customer contact and recorded M-Pesa details.</p></div><div class="summary"><span><b>{{ store.orders.length }}</b> orders</span><span><b>{{ money(store.orderTotal) }}</b> order value</span><span><b>{{ store.recordedReferences }}</b> references recorded</span></div></div><div class="filters card"><label>Search order or customer<div class="input-icon"><span class="material-symbols-outlined">search</span><input v-model="store.query" placeholder="SC-1001, name, email or phone"></div></label><label>Status<select v-model="store.status"><option value="all">All statuses</option><option v-for="item in store.statuses" :key="item" :value="item">{{ label(item) }}</option></select></label><button class="outline" @click="store.query = ''; store.status = 'all'">Clear filters</button></div><div class="card table-card"><table><thead><tr><th>Order</th><th>Customer</th><th>Customer phone</th><th>M-Pesa reference</th><th>Expected amount</th><th>Order status</th></tr></thead><tbody><tr v-for="order in store.filteredOrders" :key="order.id" @click="store.openOrder(order)"><td class="white"><strong>{{ order.order_number }}</strong><small>{{ date(order.created_at) }}</small></td><td><div class="white">{{ order.customer_name }}<small>{{ order.customer_email || 'No email supplied' }}</small></div></td><td>{{ order.customer_phone || '—' }}</td><td><code class="payment-reference">{{ order.mpesa_payment?.mpesa_reference || '—' }}</code></td><td class="amount">{{ order.mpesa_payment ? money(order.mpesa_payment.amount) : '—' }}</td><td><span class="badge" :class="statusClass(order.status)">{{ label(order.status) }}</span></td></tr><tr v-if="!store.loading && !store.filteredOrders.length"><td colspan="6" class="empty-row">No orders match these filters.</td></tr></tbody></table></div></section>
      <section v-else-if="store.activeView === 'customers'" class="page"><div class="page-heading"><div><p class="eyebrow">Derived from delivery orders</p><h3>Customers</h3><p>Customer records are grouped from existing delivery orders.</p></div></div><div class="card table-card"><table><thead><tr><th>Customer</th><th>Contact</th><th>City</th><th>Orders</th><th>Total spend</th><th>Last order</th></tr></thead><tbody><tr v-for="customer in store.customers" :key="customer.email || customer.phone || customer.name"><td class="white">{{ customer.name }}</td><td>{{ customer.email || customer.phone || '—' }}</td><td>{{ customer.city }}</td><td>{{ customer.orders }}</td><td class="amount">{{ money(customer.spend) }}</td><td>{{ date(customer.lastOrder) }}</td></tr></tbody></table></div></section>
      <section v-else-if="store.activeView === 'products'" class="page"><div class="page-heading"><div><p class="eyebrow">Store catalogue</p><h3>Products</h3><p>Control products available to the storefront checkout.</p></div></div><div class="card table-card"><table><thead><tr><th>Product</th><th>Product ID</th><th>Price</th><th>Updated</th><th>Availability</th></tr></thead><tbody><tr v-for="product in store.products" :key="product.id"><td><div class="catalogue-product"><img :src="productImageUrl(product.id)" :alt="product.name"><span class="white">{{ product.name }}</span></div></td><td>{{ product.id }}</td><td class="amount">{{ money(product.price) }}</td><td>{{ date(product.updated_at) }}</td><td><button class="badge toggle" :class="product.is_active ? 'green' : 'red'" @click="store.toggleProduct(product)">{{ product.is_active ? 'Active' : 'Inactive' }}</button></td></tr></tbody></table></div></section>
      <section v-else-if="store.activeView === 'delivery-methods'" class="page"><div class="page-heading"><div><p class="eyebrow">Checkout configuration</p><h3>Delivery methods</h3><p>Methods and costs used when a customer places an order.</p></div></div><div class="method-grid"><article v-for="method in store.deliveryMethods" :key="method.id" class="card method-card"><span class="material-symbols-outlined">local_shipping</span><div><h4>{{ method.name }}</h4><p>{{ method.id }}</p></div><strong>{{ money(method.cost) }}</strong><span class="badge" :class="method.is_active ? 'green' : 'red'">{{ method.is_active ? 'Active' : 'Inactive' }}</span></article></div></section>
      <section v-else-if="store.activeView === 'order-detail' && store.selectedOrder" class="page detail"><button class="back" @click="store.navigate('orders')"><span class="material-symbols-outlined">arrow_back</span>Orders</button><div class="detail-bar"><div><span class="badge" :class="statusClass(store.selectedOrder.status)">{{ label(store.selectedOrder.status) }}</span><p>Created {{ date(store.selectedOrder.created_at) }}</p></div><label>Update fulfilment status<select v-model="store.statusDraft"><option v-for="item in store.statuses" :key="item" :value="item">{{ label(item) }}</option></select></label><button class="primary" :disabled="store.loading" @click="store.updateStatus">Save status</button></div><div class="detail-grid"><div><article class="card detail-card"><h4><span class="material-symbols-outlined">shopping_bag</span>Order items</h4><div v-for="item in store.selectedOrder.delivery_order_items" :key="item.id" class="line-item"><img class="product-img" :src="productImageUrl(item.product_id)" :alt="item.product_name"><div><strong>{{ item.product_name }}</strong><p>Product ID: {{ item.product_id }}</p></div><div class="item-price">{{ money(item.unit_price) }}<small>Qty: {{ item.quantity }}</small></div></div><div class="total"><span>Subtotal</span><span>{{ money(store.selectedOrder.subtotal) }}</span><span>Shipping · {{ store.selectedOrder.delivery_method }}</span><span>{{ money(store.selectedOrder.shipping_cost) }}</span><b>Total</b><b>{{ money(store.selectedOrder.total) }}</b></div></article><article class="card detail-card"><h4><span class="material-symbols-outlined">confirmation_number</span>M-Pesa reference</h4><template v-if="store.selectedOrder.mpesa_payment"><div class="payment-grid"><span>Transaction reference</span><strong><code class="payment-reference">{{ store.selectedOrder.mpesa_payment.mpesa_reference || '—' }}</code></strong><span>Expected amount</span><strong>{{ money(store.selectedOrder.mpesa_payment.amount) }}</strong><span>Customer phone</span><strong>{{ store.selectedOrder.customer_phone || '—' }}</strong></div></template><p v-else class="muted">No M-Pesa payment record exists for this order.</p></article></div><aside class="side-details"><article class="card detail-card"><h5>Delivery contact</h5><p><small>Customer</small>{{ store.selectedOrder.customer_name }}</p><p><small>Contact</small>{{ store.selectedOrder.customer_email || '—' }}<br>{{ store.selectedOrder.customer_phone || '' }}</p><p><small>Delivery address</small>{{ store.selectedOrder.address }}<br>{{ store.selectedOrder.city }} {{ store.selectedOrder.postal_code || '' }}</p></article><article class="card detail-card"><h5>Delivery instructions</h5><p class="notes">{{ store.selectedOrder.delivery_notes || 'No delivery instructions supplied.' }}</p></article></aside></div></section>
    </main>
  </div>
</template>
